Result型 -> State型への変更
Wansuko-cmd/Passon pull request #13
Opened 2022-01-30 02:35 UTC by Wansuko-cmd

# 概要

- kotlin.Result型を削除して、自分で作成したState型に置き換えました
- プルリクエストとして作成するまでもなさそうな作業を行いました（名前の変更、プルリクテンプレートの作成）

### 実装したところ

1. Result型を削除
2. utilsプロジェクトを新たに作成し、androidプロジェクト内にあったState型を引っ越し
3. Flowを用いて、UseCaseからデータを配布する形に変更
4. State型にmapBothを生やして、読みやすく改善

### 懸念点

特になし

2022-01-30 05:14 UTC, Index197511 reviewed
データの流れがきれいになっていてめっちゃよいです:rocket:
PRのテンプレート設定も助かります！！

2022-01-30 05:14 UTC, Index197511 commented on core/usecase/src/main/kotlin/com/wsr/passwordgroup/GetPasswordGroupUseCase.kt
> +        _data.emit(State.Success(passwordGroup))
副作用のある動作をわけて記述できてるのいいですね:+1:

2022-01-30 05:14 UTC, Index197511 commented on core/usecase/src/main/kotlin/com/wsr/passwordgroup/GetPasswordGroupUseCase.kt
> +    val data get() = _data.asStateFlow()
Stateの初期値に`State.Empty`みたいなのを追加することを考えてもいいですね！
今の状態だとStateFlowなのでSubscribeした瞬間に初期値であるLoadingが返却されるようになっています。
考えにくいのですが、画面に遷移してきてからfetchするまでに時間がかかる場合(他の作業をアプリのユーザーが行っている)にfetchを行っていないのにLoadingのProgressBarが長時間表示されてしまうことが考えられます。
これを防ぐために`State.Empty`を追加するか、SharedFlowにするかのどちらかで対処するのがよいかもしれません！
対処するかどうかはお任せします！(こういうUIに関する問題を後でまとめて修正する形でもいいかも:+1:)

2022-01-30 11:48 UTC, ymdkit approved these changes

2022-01-30 12:48 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
ViewModelでは購読せずに `getPasswordGroupUsecase.data` をcombineしたflowを作るだけで良いかもしれませんね(View側で購読するので) ✏️ 

ちょっと他の人の意見も聞きたい所ですが @ymdkit @Index197511 

具体的なコードだとこんなイメージです 💭 
```kotlin
val uiState = MutableStateFlow(IndexUiState())
  .combine(getPasswordGroupUseCase.data) { uiState, state ->
    uiState.copy(passwordGroupsState = state.mapBoth(
      success = { list -> list.map { it.toIndexUiState() } },
      failure = { ErrorIndexUiState(it.message ?: "") }
    ))
  }
```

2022-01-30 12:48 UTC, blackbracken commented on utils/src/main/kotlin/com/wsr/state/State.kt
> +fun <T, E, NT, NE> State<T, E>.mapBoth(success: (T) -> NT, failure: (E) -> NE): State<NT, NE> =
👍 👍

2022-01-31 00:03 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
こんな書き方もあるんですね

viewModelScopeの範囲で立てるときは `launchIn(viewModelScope)` をケツに着ける形で大丈夫でしょうか？
あと、flowOfで作成する形でも大丈夫でしょうか？

こんな感じです↓

```
val uiState = flowOf(IndexUiState())
        .combine(getPasswordGroupUseCase.data) { uiState, state ->
            uiState.copy(
                passwordGroupsState = state.mapBoth(
                    success = { list -> list.map { it.toIndexUiState() } },
                    failure = { ErrorIndexUiState(it.message ?: "") }
                ),
            )
        }.launchIn(viewModelScope)

```

2022-01-31 00:35 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
補足: StateFlowにしてViewModelのスコープで購読させるなら

```kotlin
val uiState = emptyFlow<IndexUiState>()
    // ...
    .stateIn(viewModelScope, SharingState.WhileSubscribled(), IndexUiState())
```

みたいな形で良いと思います！ 🖥️

2022-01-31 06:44 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
@blackbracken 
すみません、

前者の方は
購読する側（View）で指定されたscope内で動作する
Usecaseから値が送られてきたときは、ViewModelを通る間に変換されて（購読はしない）そのままViewが見る

後者の方は
ViewModelで購読をする。scopeはViewModelで指定したものになる
UseCaseから値が送られてきたときは、ViewModelでまず値を取得して、変換して（viewModelScope内）、StateFlowとして新たに流しなおす

みたいな解釈であっていますか？

あと、これはどっちを使う方がいいとかありますか？

2022-01-31 07:44 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
解釈大丈夫です！

これ上の返信を送ってから考えたんですが、ViewModelの存在意義を鑑みても後者のほうが良いと思います(UIの状態をキャッシュするのが正しい上に通信の面でも優しそうなので) 🙇

2022-01-31 07:48 UTC, blackbracken requested changes

2022-01-31 07:48 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexFragment.kt
> +            indexViewModel.uiState.collect { indexUiState ->
直前のレビューに伴い、 `viewLifecycleOwner.repeatOnLifecycle` で囲ってあげたほうが良いかもしれません
Fragmentが死んでいる状態で購読を受け付けて動作が不安定になる可能性があります👻

2022-01-31 08:18 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
@blackbracken 
今更気づいたのですが、後者の方は値が流れてきませんでした・・・

いろいろ試した結果、初期値を最初にも入れておく
```
val uiState = flowOf(IndexUiState())
    // ...
    .stateIn(viewModelScope, SharingState.WhileSubscribled(), IndexUiState())
```

か、stateInを先に呼び出す

```
emptyFlow<IndexUiState>()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(), IndexUiState())
```

ことで動いてくれたのですが、いまいち原因が分かりません（下の方はともかく、上は特にわからない）
何かご存じでしょうか？

2022-01-31 08:38 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
検証したんですが、恐らく空のflowだと値が流れてきていない訳ではなく、何も入っていない `IndexUiState` が流れてきてますね　予想外でした 💦 

テストコード 📝 
```kotlin
val flow = MutableStateFlow("empty")

fun main() = runBlocking {
    launch {
        flowOf<String>()
            .combine(flow) { origin, added -> "$origin $added" }
            .stateIn(this, SharingStarted.Eagerly, "initial")
            .collect { text ->
                println(text)
            }
    }

    delay(1000L)
}
```

2022-01-31 10:20 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
なるほど・・・空のflowでstateInを実行したときは最適化が勝手にかかって・・・みたいなことがあるんでしょうか

わざわざflowに値を入れるのもあれなので、先にstateflowに変換してからcombineする方式で書いてみます

2022-01-31 11:36 UTC, Index197511 commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
今更なんですが、今のところcombineする必要があまりなさそう？なので、UseCaseから流れてきた値をmapするだけでもよさそうだったりしないかな？
```
val uiState: StateFlow<IndexUiState> = getPasswordGroupUseCase.data.map { state ->
    val passwordGroupsState = state.mapBoth(
        success = { list -> list.map { it.toIndexUiState() } },
        failure = { ErrorIndexUiState(it.message ?: "") }
    )
    IndexUiState(passwordGroupsState = passwordGroupsState)
}
    .stateIn(viewModelScope, SharingStarted.WhileSubscribed(), IndexUiState())
```

2022-01-31 13:30 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
これから別のUseCaseのFlowを見る可能性が出てくることも考える（例えばApp BarでUserの名前を出すなど）と、特定のFlowで云々よりもcombineを使った方がいい感じがします？

2022-01-31 15:24 UTC, Index197511 commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
将来性を考えるなら確かにCombineを使うことがよいと思いますが、まだわからないので一旦は簡単な形に抑えておくのがよいかなとも思ったりします:rocket:

2022-01-31 20:20 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
`combine` に関しては、自分は将来性という程遠くない未来に使うであろうことを見越してのものだったので、今後のこの画面の実装方針に依ってお任せします 🌮 

stateInに関しては、最適化というよりもcombineに流れてくるデータのタイミングの問題ですね!
`stateIn` の `initialValue` は単体で流された後にupstreamのflowに対して合成するだけで、元のflowに対して変更を加える訳ではありません。なので、そもそも源流となる値が流れてこないからcombineできないものだと思われます 🖊️ 
https://github.com/Kotlin/kotlinx.coroutines/blob/3574c2feca23c3e8a1ad00b5bf92e2bf04d95060/kotlinx-coroutines-core/common/src/flow/operators/Share.kt#L307-L316

2022-01-31 22:43 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +    }
そもそも合わせる値がないからcombineできずに止まってたということですね

いろいろ考えたのですが、以下の形式で行きたいと思います

```
    val uiState = emptyFlow<IndexUiState>()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(), IndexUiState())
        .combine(getPasswordGroupUseCase.data) { uiState, state ->
            uiState.copy(
                passwordGroupsState = state.mapBoth(
                    success = { list -> list.map { it.toIndexUiState() } },
                    failure = { ErrorIndexUiState(it.message ?: "") }
                ),
            )
        }
```

・拡張性がある
・そこまで書くのが困難なものではない
・初期値を複数個所で宣言するのは面倒かつややこしい

が主な理由です

改めてCoroutineあたりの知識が全然ない（特にFlow）ことが身にしみてわかりました（初めて知ったメソッドばかりだった）
また勉強していきたいです

2022-02-01 02:11 UTC, merged