ログイン機能を追加
Wansuko-cmd/Passon pull request #33
Opened 2022-03-13 08:04 UTC by Wansuko-cmd

# 概要
ログイン機能を実装しました（写真がでかくてすみません・・・）
![image](https://user-images.githubusercontent.com/63241922/158050808-67bb55ce-88ba-45e9-8320-0e2507ac5dd3.png)

### 実装したところ
指紋認証機能を追加（指紋認証のできない機体では表示されない）
![image](https://user-images.githubusercontent.com/63241922/158050829-a625e64a-385b-4afc-924f-c164f3687c78.png)

パスワードの入力でのログイン機能も追加（現在はPasswordでログイン可）

### 懸念点
ログインした後に、ナビゲーションのPopを整理してLoginページに戻れないようにしたいが、どのようにすればいいのかわからなかった

よろしくお願いします

2022-03-13 08:15 UTC, Index197511 commented
画像サイズは`<img>`タグで指定するといいよ:+1:

2022-03-13 08:19 UTC, Index197511 commented
指紋認証組み込めててすごい....

2022-03-13 08:24 UTC, Index197511 commented
> ログインした後に、ナビゲーションのPopを整理してLoginページに戻れないようにしたいが、どのようにすればいいのかわからなかった

こういうのがあるみたい:eyes:
https://qiita.com/jumperson/items/f856868181ef586db461

よくあるかつ対応しやすい(公式にもサンプルがある)のはback pressedを上書きして無効にする形かな？
僕はこれがいいと思います！
https://developer.android.com/guide/navigation/navigation-custom-back

2022-03-13 08:34 UTC, Index197511 reviewed
詳しいレビューはレビュワーにあたっている人にお任せします！

2022-03-13 08:34 UTC, Index197511 commented on android/app/src/main/java/com/wsr/index/IndexFragment.kt
> +        (requireActivity() as AppCompatActivity).supportActionBar?.show()
ここにBackArrowを表示しない対応を書いてあげるとよさそう！

2022-03-13 08:34 UTC, Index197511 commented on android/app/src/main/java/com/wsr/login/LoginFragment.kt
> +                } else showMessage(getString(R.string.login_password_wrong))
UI(Fragment, Activity)で条件分岐を書く必要がある場合はUIにロジックを書いてしまっている場合が多いので一考の余地ありだと思います！
今回の場合はUI側がとる動作として`次の画面に遷移する`、`エラーメッセージを表示する`の二つなのでそれぞれを別イベントとして定義してあげる形がよいと思います！

2022-03-13 08:34 UTC, Index197511 commented on android/app/src/main/java/com/wsr/login/LoginFragment.kt
> +    }
こういう風にかけるんですね....なるほどです！

2022-03-13 10:06 UTC, ymdkit commented on android/app/src/main/java/com/wsr/login/LoginFragment.kt
> +                    Toast.makeText(requireContext(), "Error", Toast.LENGTH_LONG).show()
ここも `showMessage` 使えば良さそうです :+1:

2022-03-13 16:49 UTC, blackbracken requested changes
ナイス指紋認証 🤞 

細かい所は見られていないのでレビュワーの方にお任せして、ざっと気になったところだけレビューしています
現状だと、パスワードを入力した後エンターを押したりしても反応が無さそうです 👻

2022-03-13 16:49 UTC, blackbracken commented on android/app/src/main/java/com/wsr/login/LoginFragment.kt
> +        findNavController().navigate(R.id.index_fragment)
ここ `NavController#navigate(id)` で `IndexFragment` に飛んでますが、折角 `action_login_fragment_to_index_fragment` を作ってるので削除するか若しくはそちらを使って遷移しても良さそうですね :)

https://github.com/Wansuko-cmd/Passon/pull/33/files#diff-211c92fd6060326ba55420f6aa63788d5936fe73ac6602630820a83bca97bbb6R12-R16

加えてなんですが、上のアクションで `app:launchSingleTop="true"` してあげれば、戻るボタンのコールバックを上書きせずとも戻れなくなりそうですが如何でしょう(戻るは非表示にしなければなりませんが) 💭

2022-03-13 16:49 UTC, blackbracken commented on android/app/src/main/res/layout/fragment_login.xml
> +                android:fontFamily="@font/jetbrains_mono"
❤️

2022-03-13 16:49 UTC, blackbracken commented on android/app/src/main/java/com/wsr/login/LoginViewModel.kt
> +    fun checkPassword() {
このメソッドの呼び出すタイミングによってはパスワードチェックが行われていない場合がありそうです 👻 
メソッドを適切なタイミングですべて呼び出すか、パスワードのFlowの更新を、逐次受け取るのではなく入力が完了した時点で受け取るようにし、そのままパスワードのFlowを購読するようにしても良いかもしれません 🦘

2022-03-14 01:28 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/login/LoginViewModel.kt
> +    fun checkPassword() {
入力が完了した時点で・・・というのはcustom viewを使っている関係でうまくいかないんですよね・・・（うまくできる方法があればお願いします。ついでに編集画面の方も改善できそうです）
適切なタイミングというのはEnterを押したときも、ということでしょうか？

2022-03-14 15:18 UTC, ymshun reviewed
今のEditTextはフォームの外をクリックしてもフォーカスが外れないようになってるので、外クリックしたらフォーカス外してキーボード非表示にしたらUX上がりそう 🦾 
これはjavaだけどこんな感じのをMainActivityとかに書けば他のEditTextのフォーカス処理もハンドリングできそう
https://www.codegrepper.com/code-examples/java/how+to+remove+focus+of+edittext+in+android+when+click+outside

androidのキーボード周りは沼なのでハマったら一旦スルーした方がいいかも

2022-03-15 03:46 UTC, blackbracken commented on android/app/src/main/java/com/wsr/login/LoginViewModel.kt
> +    fun checkPassword() {
なるほど🤔 

> 適切なタイミングというのはEnterを押したときも、ということでしょうか？
そうです！Enterを押したときにチェックするだけで今回の場合解決できそうなのでそれで良さげですね 👀

2022-03-15 07:58 UTC, blackbracken commented on android/app/src/main/java/com/wsr/layout/LayoutTextField.kt
> +            false
エンターの入力はこのメソッドで消費されるので、`block` を実行したときは `true` を返却したほうが良いかもしれないですね 🌡️ 
https://developer.android.com/reference/android/widget/TextView.OnEditorActionListener.html#onEditorAction

2022-03-15 07:58 UTC, blackbracken commented on android/app/src/main/java/com/wsr/login/LoginFragment.kt
> +                    }
nits: 別のコミットに分けたい

2022-03-15 07:58 UTC, blackbracken commented on android/app/src/main/java/com/wsr/MainActivity.kt
> +                if(!rect.contains(event.rawX.toInt(), event.rawX.toInt())) {
どちらもX座標になってしまってるかも 🗺️

2022-03-15 07:58 UTC, blackbracken commented on android/app/src/main/java/com/wsr/MainActivity.kt
> +            val view = currentFocus
ここから先のコードは、僕なら別のメソッド( `closeKeyboardIfTapOutside(tappedX: Int, tappedY: Int)` のような)に機能的凝集の観点から分割しちゃうかもです 💭

2022-03-15 07:58 UTC, blackbracken commented on android/app/src/main/java/com/wsr/MainActivity.kt
> +            if(view is EditText) {
上のレビューのようにすると、`dispatchTouchEvent` の返り値を返す責任をここでは負わなくてよくなるので、`val view = currentFocus as? EditText ?: return` みたいに書けそうです 🐰

2022-03-15 09:23 UTC, blackbracken approved these changes
🔢

2022-03-15 09:35 UTC, merged