[fix] suspendをかませて実装
Wansuko-cmd/Passon pull request #7
Opened 2022-01-26 14:03 UTC by Wansuko-cmd

Discordで書いていたことを実装してみました

1. ViewからViewModelにデータを取得するように要請
2. ViewModelがUseCaseにデータを要請
3. UseCaseがRepositoryにデータを要請
4. Repositoryがデータを取得
5. UseCaseがRepositoryから来たデータをState(Result型)でラップ
6. ViewModelが、ローディング中から、UseCaseから来た値にデータを入れ替え
7. Viewが、ViewModelから出ているFlowから値を確認

という流れです

StateはSuccessとFailureの二つの値を持つResult型です。
これはKotlin Resultの方に乗り換えてもいいと思ってます。

よろしくお願いします

2022-01-26 17:31 UTC, blackbracken commented on utils/src/main/kotlin/com/wsr/state/State.kt
> +sealed class State<out T> {
kotlin-resultを導入するなら気にしなくて良い所ですが、現状だと別の型として実装する恩恵が小さそうなので、
```kotlin
typealias State<T> = kotlin.Result<T>
```
のようにエイリアスにしてしまっても良いかもしれません。

2022-01-26 17:31 UTC, blackbracken commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                )
この場合だとsuspendなメソッドにするのが一番適切に見えます 👍

2022-01-26 23:19 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                )
UseCaseはsuspendで実装することが一番適切、という認識であっていますか？

2022-01-27 00:47 UTC, ymdkit requested changes

2022-01-27 00:47 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
`isFetching` という変数名からは「読み込み中」かどうかを表す Bool 値ということが読み取れるものの、 Fragment 側での使われ方を見る感じ「読み込み完了」かどうかを表しているように見えます。

State は状態を表すためのもので「読み込み完了した」という一時的な結果というよりも、それによって「読み込み中でなくなった」という最終的な状態を表すためのものなので、`isFetching` の値は以下のように遷移するのが良いと思います

読み込み前 → false
fetch 開始時 → true
fetch 終了 → false

また、これに伴い Fragment 側での扱いも以下のようになると良さそうです

```
indexViewModel.uiState.collect {
    if (it.isFetching) {
        // プログレスバーの表示制御
    }
    if(it.passwordGroups.isNotEmpty()){
        // パスワードグループ一覧のリスト表示
    }
}
```

2022-01-28 01:49 UTC, Wansuko-cmd commented
夢中で作業した結果、コミットの粒度がかなり大きくなっております、すみません

2022-01-28 01:53 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
falseにし忘れが起きてしまって怖かったので、

```
sealed class State<T, E> {
    class Loading<T, E> : State<T, E>()
    class Success<T, E>(val value: T) : State<T, E>()
    class Failure<T, E>(val value: E) : State<T, E>()
}
```

として、Loading->Success or Failure（Either型みたいにしておいて、成功か失敗かで型を変える）
という感じにして、Fragmentでは

```
indexViewModel.uiState.collect {
    it.passwordGroups
        .onLoading { }
        .onSuccess { list -> indexAdapter.submitList(list) }
        .onFailure { state ->
            Toast.makeText(context, state.message, Toast.LENGTH_LONG).show()
        }
}
```

という感じにしてみました、どうでしょうか？

2022-01-28 02:31 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
全ての状態が排反であるならば、 sealed class を用いて列挙する形で現状特に問題ないです！

逆に、今後状態の重なり合いが起きるのであれば、`isHogeHoge` のような値を State に持たせるようにする（つまり、元の実装方針に戻す）こともあり得ます。

【理由】
今は「読み込み状態」という一つの状態を監視しているので 3パターンを列挙すれば良いが、ここに「プレミアム会員かどうか」「ログイン済みか」といった複数の要素が絡んでくると、パターンの数が爆発的に増えていくため、列挙するよりも State にフラグを持たせる実装の方が都合が良い

2022-01-28 02:39 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
また、Fragment の実装について、  `onHogeHoge` を独自に実装して Kotlin 標準の Result ぽくするのも良さそうですが、自分としては状態の考慮漏れを防ぐためにも when を使うのをオススメしたいです。

網羅していない場合に ↓の画像のような警告を出してくれます （今後の Kotlin のバージョンではそもそも網羅していない when が禁止されるようです）
<img width="846" alt="スクリーンショット 2022-01-28 11 39 32" src="https://user-images.githubusercontent.com/25548427/151477763-135c6345-49bf-4702-824b-3e89dd5e838c.png">

実装例
```
                when(it.passwordGroups){
                    is State.Loading -> {}
                    is State.Success -> {}
                    is State.Failure -> {}
                }
```

2022-01-28 05:13 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
![image](https://user-images.githubusercontent.com/63241922/151490964-0f3d50e4-d251-4800-8db3-ac63c5556cdc.png)

前回のミーティングの時の課題に自分も当たってしまうとは
Whenを使えば確かに考慮漏れがなくなるので採用したいのですが、これは何とかならないのでしょうか？

2022-01-28 05:18 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
> 全ての状態が排反であるならば、 sealed class を用いて列挙する形で現状特に問題ないです！
>
> 逆に、今後状態の重なり合いが起きるのであれば、isHogeHoge のような値を State に持たせるようにする（つま>> り、元の実装方針に戻す）こともあり得ます。

これは、プレミアム会員か等によって表示内容が変わる分をViewModelで吸収しようと考えています。
プレミアム会員じゃない人はフィルターがかかる部分もViewModelでフィルターをかける感じです

ViewはただViewModelから来た値をそのまま出力するように設計する、と考えると問題なさそうでしょうか？

2022-01-28 06:40 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
> Whenを使えば確かに考慮漏れがなくなるので採用したいのですが、これは何とかならないのでしょうか？

~~Kotlin の今後に期待~~ 網羅性を損なうことのないまま、 Fragment 側で利用しやすくすることを考えるならば、こんな感じの書き方がありそう。

```
fun <T, E> State<T, E>.addCallBacks(
    onLoading: () -> Unit,
    onSuccess: (T) -> Unit,
    onFailure: (E) -> Unit
) = when (this) {
    is State.Loading -> onLoading()
    is State.Success -> onSuccess(this.value)
    is State.Failure -> onFailure(this.value)
}
```

```
            indexViewModel.uiState.collect {
                it.passwordGroups.addCallBacks(
                    onLoading = {},
                    onSuccess = {},
                    onFailure = {}
                )
            }
```

2022-01-28 06:42 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
> これは、プレミアム会員か等によって表示内容が変わる分をViewModelで吸収しようと考えています。
プレミアム会員じゃない人はフィルターがかかる部分もViewModelでフィルターをかける感じです

View 側の制御に関係しない（ViewModel のみで使用する）想定であれば問題ないです！ 🙆‍♂️

2022-01-28 07:18 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexUiState.kt
> +    val passwordGroups: State<List<PasswordGroupIndexUiState>, ErrorIndexUiState> = State.Loading(),
seald class で扱うように変更すると、ここの `passwordGroups` っていう変数名に違和感があるから、 変数名は `state` とかの方が良さそう。

その上で、 state フィールド1つで全ての情報を詰め込むのならば、そもそも `IndexUiState` は `class` ではなく `typealias` でも良い気がする（アクセスする際の記述量も減らせる）

```
typealias IndexUiState = State<List<PasswordGroupIndexUiState>, ErrorIndexUiState>
```

ViewModel 側
```
    private val getPasswordGroupUseCase = GetPasswordGroupUseCase()

    private val _uiState = MutableStateFlow<IndexUiState>(State.Loading())
    val uiState = _uiState.asStateFlow()

    fun fetchPasswordGroup(email: String) {
        viewModelScope.launch {
            getPasswordGroupUseCase
                .getAllByEmail(email)
                .map { list -> list.map { it.toIndexUiState() } }
                .mapBoth(
                    success = { list ->
                        _uiState.update {
                            State.Success(list)
                        }
                    },
                    failure = { error ->
                        _uiState.update {
                            State.Failure(ErrorIndexUiState(error.message ?: ""))
                        }
                    }
                )
        }
    }
```

2022-01-28 08:23 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexUiState.kt
> +    val passwordGroups: State<List<PasswordGroupIndexUiState>, ErrorIndexUiState> = State.Loading(),
確かに、名前にStateを付けた方がよさそうですね！

一応Stateフィールドはそれぞれの情報ごとに区切ろうかなと思っています
例えばApp barに名前を、真ん中にパスワードグループ一覧を持ってくるとしたら

```
data class IndexUiState(
    userState: State<UserIndexUiState, ErrorIndexUiState>
    passwordGroupsState: State<List<PasswordGroup>>, ErrorIndexUiState>
)

```

それで分けておいた方がいいのかなと感じています（そもそも最初のisFetchingの命名がダメでした・・・）
ErrorIndexUiStateが共通なのは、エラーの内容を表示する方法は一通りの方がいいかなということでまとめています

2022-01-28 11:40 UTC, Wansuko-cmd commented on android/app/src/main/java/com/wsr/index/IndexViewModel.kt
> +                        _uiState.update { it.copy(isFetching = true, passwordGroups = list) }
なるほど・・・この方法でやってみます！

2022-01-29 04:34 UTC, merged

2022-01-29 04:37 UTC, ymdkit commented on android/app/src/main/java/com/wsr/index/IndexUiState.kt
> +    val passwordGroups: State<List<PasswordGroupIndexUiState>, ErrorIndexUiState> = State.Loading(),
> 一応Stateフィールドはそれぞれの情報ごとに区切ろうかなと思っています

その予定であれば変数名だけ変えるので問題ないと思います 🙆‍♂️